In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/employee_salary.csv")

In [4]:
df.head()

   Age  Experience_Years  Education  Job_Level    Department  Salary
0   22                 0  Bachelors          1            IT  300000
1   24                 1  Bachelors          1            IT  350000
2   25                 2  Bachelors          1       Finance  380000
3   26                 3  Bachelors          2            IT  450000
4   27                 4    Masters          2  Data Science  550000

In [5]:
df.shape

(20, 6)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               20 non-null     int64
 1   Experience_Years  20 non-null     int64
 2   Education         20 non-null     str
 3   Job_Level         20 non-null     int64
 4   Department        20 non-null     str
 5   Salary            20 non-null     int64
dtypes: int64(4), str(2)
memory usage: 1.3 KB

In [7]:
df.columns

Index(['Age', 'Experience_Years', 'Education', 'Job_Level', 'Department',
       'Salary'],
      dtype='str')

In [10]:
df.describe()

             Age  Experience_Years  Job_Level        Salary
count  20.000000         20.000000  20.000000  2.000000e+01
mean   34.650000         11.750000   3.750000  1.010000e+06
std     8.998684          9.031378   1.860249  5.565779e+05
min    22.000000          0.000000   1.000000  3.000000e+05
25%    27.750000          4.750000   2.000000  5.875000e+05
50%    32.500000          9.500000   4.000000  8.750000e+05
75%    40.500000         17.500000   5.000000  1.412500e+06
max    52.000000         30.000000   7.000000  2.200000e+06

In [11]:
df.describe(include='object')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8404\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       Education    Department
count         20            20
unique         3             3
top      Masters  Data Science
freq          10            11